### ISSUE TITLE
Encoding problem

### ISSUE THREAD

**Issue by navi8602** [qualialabs/reval#10]
When used as a package for Meteor
When editing in Google Chrome browser, there are problems with the Russian language in the template

http://take.ms/yQ4Tgl

**Comment by veered** [comment]
Good catch! Could you post a sample file with this issue?

**Comment by veered** [comment]
I'll reopen this issue if you post a sample file

**Comment by navi8602** [comment]
Sorry for the delay, here is an example file 
[https://raw.githubusercontent.com/navi-creator/health/master/client/admin/dashboard/adminDashboard.html?token=ABw4-Nm3SaeFhe7LVVpd5_RVMvJq6gdXks5ZRhqAwA%3D%3D](url)

**Comment by veered** [comment]
Thanks! Turns out that the issue was with Base64 encoding/decoding UTF-8 strings. I figured out a fix, and will include it with the next release. Should be sometime this week.

**Comment by veered** [comment]
The fix for this has now been released w/ version 0.2.0
