### ISSUE TITLE
No ability to wrap code.

### ISSUE THREAD

**Issue by destinatis** [qualialabs/reval#12]

**Comment by veered** [comment]
Gonna need some more information haha

**Comment by destinatis** [comment]
You know this... http://nebulon.s3.amazonaws.com/uxZGtJAH.png 
All best IDEs have it.

**Comment by veered** [comment]
We can support anything that https://github.com/Microsoft/monaco-editor supports (the core editor that VS Code is based on).

I'd have to look into it more to figure out if that's supported. I'll get back to you soon

**Comment by destinatis** [comment]
Doesn't look like it has wrapping.

**Comment by veered** [comment]
Damn... have you tried the editor plugins for Reval? It's more convenient for heavy editing than the in-browser editor.

**Comment by destinatis** [comment]
No sure, what you mean? I tried Atom but it does not reload as fast as yours. If you can recommend a good set up, I'd appreciate it. I need to be able to edit multiple files and at least fold functions.

**Comment by veered** [comment]
There are Reval plugins for a few editors right now, but I don't believe one exists for Atom right now. It is super easy to add new ones though! Here's the current list:

https://github.com/qualialabs/reval/tree/master/plugins

The Sublime one in particular shows how simple it is: https://github.com/qualialabs/reval/blob/master/plugins/sublime.py

**Comment by destinatis** [comment]
Thanks! Will give it a try tomorrow.

**Comment by veered** [comment]
Alright turns out that you can fold lines! I just had to turn on an option in Monaco.

The commands are `Cmd+Alt+[` and `Cmd+Alt+]`. More generally, if you type `Cmd+Shift+P` it will open up the Command Palette, and you can search over different actions you can take (including folding).

I'll release these changes later today.

**Comment by destinatis** [comment]
nice!

**Comment by veered** [comment]
The fix for this has now been released w/ version 0.2.0
