### ISSUE TITLE
Live Reload For Atom

### ISSUE THREAD

**Issue by destinatis** [qualialabs/reval#13]
How do I do it?

**Comment by veered** [comment]
Implement a plugin for Atom similar to the one for Sublime: https://github.com/qualialabs/reval/blob/master/plugins/sublime.py

**Comment by janat08** [comment]
you just need to send a POST request to the Meteor server containing the code and file path of the file you'd like to reload

**Comment by janat08** [comment]
If you're there, apparently something along this lines would work except for "unmatched OUTDENT", if you stick it into init file. I don't actually know coffeescript.
```
# initialization file (not found)
http = require('http')

atom.commands.add 'atom-text-editor',
  'editor:qualia-reval': () ->
      req = http.request({
      host: 'localhost',
      port: 3000,
      path: '/reval/reload?filePath=' + atom.workspace.getActiveTextEditor().getTitle(),
      method: 'POST'
    });
    req.write(atom.workspace.getActiveTextEditor().getBuffer().getText());
    req.end();
```
The original post for help: https://discuss.atom.io/t/translate-4-line-sublime-package-please/44529/5

**Comment by destinatis** [comment]
Thank you @janat08! I ended up modifying it slightly and here is what I am currently working with.

```
http = require('http')

atom.workspace.observeTextEditors (editor) ->
  editor.onDidChangeCursorPosition ->
    req = http.request({
      host: 'localhost',
      port: 3000,
      path: '/reval/reload?filePath=' + atom.workspace.getActiveTextEditor().getTitle(),
      method: 'POST'
    });
    req.write(atom.workspace.getActiveTextEditor().getBuffer().getText());
    req.end();
```
Cheers!

**Comment by janat08** [comment]
so this watches mouse then?

**Comment by destinatis** [comment]
No, it watches the cursor. Every time you type it reloads. If you know a way of how to make it work only for projects that contains reval and everything, feel free to let me know. :)

**Comment by janat08** [comment]
I imagine if you try and figure out if port 3000 is active you then could if (true) onDidChange...

**Comment by destinatis** [comment]
True, the problem is that I run a lot of different stuff on 3000.

**Comment by janat08** [comment]
well then set up scripts in both atom and the package that try and find each other :D. That is whoever start's last posts to the other and await for confirmation.

**Comment by veered** [comment]
This is my suggested way of dealing w/ this problem: https://github.com/qualialabs/reval/issues/3

This technique is only implemented in the Spacemacs plugin at the moment.

**Comment by janat08** [comment]
although automatic updating from atom can get ugly if you're fixing hard errors that reload meteor which means that it stops receiving page saves or something, what you wind up with is several files that are saved on atom, but are patched with old versions before the save. Clear all with alert would help.

**Comment by janat08** [comment]
I suspect it goes so far as to seriusly screw with app, in such a way that anomalies.

**Comment by ottobonn** [comment]
Here you go: https://atom.io/packages/atom-reval
