### ISSUE TITLE
Cursor Position Lost on Hot Reload (Live)

### ISSUE THREAD

**Issue by matteodem** [qualialabs/reval#14]
When I try to change code in the reval editor for komentify the cursor in the inline editor jumps out as soon as the file is hot reloaded. 

**Expected**: The cursor stays in the editor.

**Comment by matteodem** [comment]
For additional context, I'm using the useraccounts package which for some reason seems to autofocus into the email / username input field.

**Comment by veered** [comment]
Have you tried disabling the `focusFirstInput` option?

https://github.com/meteor-useraccounts/core/blob/e5bb229fa7c87d3f275c3c822af47a674284b382/lib/templates_helpers/at_input.js#L7

**Comment by matteodem** [comment]
No I didn't, thanks for the hint! Since this issue has to do with the user accounts having some focus logic I'll close this ticket.
