### ISSUE TITLE
Jade support

### ISSUE THREAD

**Issue by juho** [qualialabs/reval#2]
..would be nice!

Would it just be up to adding another case around here: https://github.com/qualialabs/reval/blob/master/packages/qualia_reval/server/reload.js#L42 ? I can do a PR later this week.

**Comment by veered** [comment]
Yep, just need to check the file extension and figure out how to turn the update into an eval string

**Comment by veered** [comment]
Jade is now supported

**Comment by juho** [comment]
Thanks, I ended up making a little hack locally that worked but never had the time to make a full PR :) would you mind using the pacreach:jade package instead? That's the one in the guide as well.
