### ISSUE TITLE
Does this work with Meteor 1.4+?

### ISSUE THREAD

**Issue by 1jerry** [qualialabs/reval#22]
I have no "</>" on my screen, and ctrl-click or ctrl-i does nothing, so I have no way of triggering the editor.  _but_ if I change my URL ad add /reval/edit shows a [blank] editor.  Since there is no messages of any kind to give me a clue, I need help to track down what the issue could possibly be.

I had no errors adding the package, building my app, and no errors in the console.  I see the qualia_reval.js files in my build.  I am running on port 3000.

Using Chrome 61 on Windows 10 using Meteor version 1.4.2.3 with FlowRouter, ViewModel.

**Comment by veered** [comment]
Reval doesn't work on Windows (well the browser can be on windows, but the Meteor server has to be running on OSX or Linux). It wouldn't be all that hard to port it, but right now it relies on a few Unix-like command line utilities.

However, I am surprised that the "</>" icon is not showing up. Have you checked the DOM to see if it is there but hidden behind other elements?

**Comment by 1jerry** [comment]
Since I have GNU Linux utilities installed and I an pretty good at tracking things down using Chrome debugger and process monitoring if I have a starting point, I thought I would give it a try.  My landing page is pretty simple and there is _nothing_ injected into the page and no triggers work from the keyboard, even though I see your code in the build folder.  So since I have no messages about what the problem could be, I have no starting point to give you (or me) for figuring out the issue.  If you don't have any other suggestions, I guess I start putting console.log's in your package's code.  In that case it would be helpful to know what functions _should_ be fired when starting up and/or rendering a page.

The version installed shows 0.0.5.  Grepping the package I don't find the string "</>".  The qualia_reval.js file is being loaded in a <script>.
One additional piece of information: it is creating the "reval" collection.  It has one item with an empty "payload" property.

**Comment by veered** [comment]
That's a really old version of Reval; the most recent published version is 0.2.0. I bet that's the main problem.

**Comment by 1jerry** [comment]
AHA!  We found the right clue.  Most everything seems to be working now.

Funny, I did a normal "meteor add..." command to add the package.  I had to do a "Meteor update..." to get the correct version.  (OK, not funny).  I looked for a version number reference on your README.md and didn't find one, so I _assumed_ the Meteor add command would get the correct one.

Thanks for the quick response!

**Comment by veered** [comment]
No problem!
