### ISSUE TITLE
Pass hostname/port

### ISSUE THREAD

**Issue by juho** [qualialabs/reval#3]
Would be cool if the hostname/port could be configured per project somehow. We have a few apps that run at the same time on different ports.

**Comment by veered** [comment]
Yeah we're actually in a similar situation, we run our app on `qualia:80`. One solution is to create `.revalrc` that contains host:port info and when a file is modified, the plugin walks up the source tree from the file being reval'ed until it finds a `.revalrc` and then sends the info there

**Comment by jlukic** [comment]
The sublime plugin includes a [full set of config params](https://github.com/qualialabs/reval-sublime/blob/master/MeteorReval.sublime-settings)
https://github.com/qualialabs/reval-sublime

**Comment by veered** [comment]
@jlukic But you still wouldn't be able to work on multiple meteor projects at the same time with editor-wide configs

**Comment by juho** [comment]
Could one possibly include the host/port in the sublime project config? I haven't dug into plugin creation at all so no idea.

**Comment by veered** [comment]
Haven't updated the repo yet but here's my Spacemacs implementation of using `.revalrc`:
```
(defun qlm--base-path (start-path)
  (require 'f)
  (f-traverse-upwards (lambda (path) (f-exists? (f-expand ".meteor" path))) start-path)
)

(defun qlm--base-url (base-path)
  (require 'f)
  (let ((revalrc (f-join base-path ".revalrc")))
    (if (f-exists? revalrc) (f-read-text revalrc) "localhost:3000")
  )
)

(defun qlm--url (path)
  (require 'f)
  (let ((base-path (qlm--base-path path)))
    (if base-path
        (concat "http://" (qlm--base-url base-path) "/reval/reload?filePath=" (f-relative path base-path))
        (concat "http://localhost:3000/reval/reload?filePath=" path)
    )
  )
)

(defun qlm--reload ()
  (require 'request)
  (interactive)
  (request
    (qlm--url (buffer-file-name))
    :type "POST"
    :data (buffer-string)
  )
)
```

**Comment by veered** [comment]
I've been using this the `.revalrc` way, and it's been working very well
