### ISSUE TITLE
No such file or directory on windows

### ISSUE THREAD

**Issue by Jarskih** [qualialabs/reval#4]
Trying to edit file using url: http://localhost:3000/reval/edit?filePath=C:\Meteor\frontend\client\main.html

The path is not correct on Windows 10. Meteor 1.4.3.1

```
Error: ENOENT: no such file or directory, open 'C:\Meteor\frontend\.meteor\local\build\programs\server\Meteor♀rontendclientmain.html'
W20170227-10:45:18.605(8)? (STDERR)     at Error (native)
W20170227-10:45:18.606(8)? (STDERR)     at Object.fs.openSync (fs.js:549:18)
W20170227-10:45:18.608(8)? (STDERR)     at Object.fs.writeFileSync (fs.js:1156:15)
W20170227-10:45:18.610(8)? (STDERR)     at packages/qualia:reval/server/editor.js:114:6
W20170227-10:45:18.611(8)? (STDERR)     at doCall (packages\meteorhacks_picker.js:128:14)
```

Steps to reproduce:

meteor create frontend
meteor add qualia:reval
go to url http://localhost:3000/reval/edit?filePath=filepath

**Comment by veered** [comment]
Does it work if you use forward slashes?

**Comment by tcastelli** [comment]
I was actually trying this to develop the webstorm plugin and got it solved by doing this:
```
const isWin = /^win/.test(process.platform);
    if (isWin) filePath = filePath.replace(/\\/g,"/");
```
However I found another bug related to textarea.
I'll open an Issue and a PR for the changes

**Comment by veered** [comment]
I've merged the @tcastelli PR and pushed the new version of the package to Atmosphere. @Jarskih can you verify it works?

**Comment by Jarskih** [comment]
Excellent. Works now with both forward and backward slashes.

**Comment by veered** [comment]
Cool
