### ISSUE TITLE
Error when code contains <textarea> ... </textarea>

### ISSUE THREAD

**Issue by tcastelli** [qualialabs/reval#6]
I found out that if code contains a textarea, the content read omits everything after the </textarea>.
Any suggestion to improve that part?

I though about maybe commenting all the code before parsing and then uncomment

**Comment by veered** [comment]
Is this only when using the in-browser code editor?

**Comment by tcastelli** [comment]
Not sure, I have only tried with the in-browser editor while trying to setup the webstorm plugin development. Could you try with the in-browser editor to verify the issue?

**Comment by veered** [comment]
Should be fixed
